### ISSUE TITLE
Email Distributions Issues

### ISSUE THREAD

**Issue by dspencer-kc** [dspencer-kc/mawd-pm#12]
There appears to be issues with result emails being distributed.  One examples is every case by Mill Creek Middle School.  Also - the date time distributed through email is not being tagged.

![image](https://user-images.githubusercontent.com/10395841/102096781-b435d300-3dea-11eb-9c3b-19d70bb1e63d.png)

![image](https://user-images.githubusercontent.com/10395841/102095845-9fa50b00-3de9-11eb-8f23-28c1dc5e3ca4.png)

**Comment by ebergee** [comment]
I'm fairly certain that this is fixed, but I'm keeping an eye on it.
