### ISSUE TITLE
Text distribution issues

### ISSUE THREAD

**Issue by ebergee** [dspencer-kc/mawd-pm#13]
Similarly to the email distribution issue, there are some problems getting texts distributed to clients.

**Comment by dspencer-kc** [comment]
This was also an issue with 20-Z224210, although I did redistribute the text around 5:00 pm 12/11 and it appears it went that time.

**Comment by dspencer-kc** [comment]
816-986-7608

**Comment by ebergee** [comment]
![text system](https://user-images.githubusercontent.com/75635666/102245921-bfa8fd00-3ec3-11eb-8ff1-2b980037f59e.PNG)
Here is an example of a patient who did not get their results, but has gotten their results previously without issue.

**Comment by ebergee** [comment]
Tentatively fixed by changing to a toll free number
