### ISSUE TITLE
Re Order Search Doesn't Function after First Search

### ISSUE THREAD

**Issue by dspencer-kc** [dspencer-kc/mawd-pm#18]
If you go to client re-order, search for a user, place and order, then go back and reach for another user, the search is broken after you return.

**Comment by dspencer-kc** [comment]
Here's video off issue if that helps

![ClientReaordSearchIssue](https://user-images.githubusercontent.com/10395841/102274960-51c3fc00-3eea-11eb-90b2-feecd8f9ee7d.gif)

**Comment by mkhadka07** [comment]
fixed: [Commit](https://github.com/bistap/mawd-webform-ui/pull/33/commits/9981f56de11556dacd1eac622838d175cb894396)
checking if value is null/undefined before converting to lowercase
