### ISSUE TITLE
Clients Marked 'DEAD' still show as an option for accession team to use

### ISSUE THREAD

**Issue by dspencer-kc** [dspencer-kc/mawd-pm#19]
In trying to manage duplicate clients, if you mark a client 'Dead', it still is usable and the accessioning team still can chose them.  As a workaround, we have been marking them dead and changing the client name to 'ZZZ DO NOT USE'.  It would be preferred to have dead clients not be allowed to be accessioned.

**Comment by dspencer-kc** [comment]
As a follow up to this, it would be helpful to have a client merge ability, where if there are duplicate clients, a power user could do a process that would mark a client as dead, then move all the accession_orders and client_orders to the other client id, and also handle the client links in c19.com that associeate user names to specific clients.

**Comment by SidHarder** [comment]
I made it so you will only see active clients when editing an Accession. I published it in test only.

**Comment by ebergee** [comment]
Looks to me that clients marked as dead in prod aren't showing up anymore as an option to order from.
