### ISSUE TITLE
Kit_registration_insurance_bill changes from original client to kit registration, won't distribute results to original client

### ISSUE THREAD

**Issue by ebergee** [dspencer-kc/mawd-pm#20]
Example test patient: 20-Z23588. Ordered a kit under "order new requisition" and registered it against a kit. Selected "bill to insurance." Came across into the LIS as Client Name: MAWD, but when accessioned it changes to Kit_Registration_Insurance_Bill and won't distribute results back to c19order portal.
![kitreg1](https://user-images.githubusercontent.com/75635666/102283514-2f38df80-3ef8-11eb-8eb0-8c7349a63c03.PNG)

**Comment by ebergee** [comment]
![kitreg3](https://user-images.githubusercontent.com/75635666/102283568-5099cb80-3ef8-11eb-8c6f-c4f1ac8c1815.PNG)

**Comment by SidHarder** [comment]
I removed the code that changes the client, so this should not happen.  I published it in test and prod

**Comment by ebergee** [comment]
Tested and works as expected
