### ISSUE TITLE
KSRegistration Updated - and corresponding data fields

### ISSUE THREAD

**Issue by dspencer-kc** [dspencer-kc/mawd-pm#30]
![image](https://user-images.githubusercontent.com/10395841/102940501-13908480-4476-11eb-86eb-d404ecf9afef.png)

If someone answers yes for this, we need to prompt for their KDHE Authorization Code.  Then on the database and within MAWDLIS, on the client table we need to add the field as Invoice_Code - just a string value without and validation

**Comment by dspencer-kc** [comment]
ALSO - just for Service Providing Establishments & Private Industries

In addition to this information, we also need to request and track the following info (at this point it is not required):

Collection Supervisor Name
Collection Supervisor Phone
Collection Supervisor Email

**Comment by ebergee** [comment]
no longer applicable
