### ISSUE TITLE
Patient Info Review - Send validation URL

### ISSUE THREAD

**Issue by bistap** [dspencer-kc/mawd-pm#31]
1. automatically select Send confirmation to patient
2. Let patient know as soon as my order is submitted to review their information
3. The patient will be able to validate the order with PIN or FN LN and DOB
4. If the patient info is validated let them see their information to review
5. If the patient cannot validate with PIN or FN LN and DOB. Let the patient know to contact me (the client submitting the order)

**Comment by ebergee** [comment]
no longer applicable
