### ISSUE TITLE
Consolidated /kit landing page

### ISSUE THREAD

**Issue by bistap** [dspencer-kc/mawd-pm#4]
update test.c19order.com/kit and test.c19order.com/kit/id/[kitid] to accept Covid 19 number.
This number could be - clientId with checksum, voucher, requisitionId

On clientId with checksum 
> BE will respond with defaults: billTo, insurace, provider, clientid, clientName values and allows the user to enter other information.
On voucher type order
> Insurance option not available
Preordered from Doc office
> This will have date of birth so ask user to validate the date of birth
> Show insurance information if it was preselected

**Comment by ebergee** [comment]
All scenarios have been tested to the best of my knowledge and everything works as expected in test.
