### ISSUE TITLE
Fix DOB on reorder issue

### ISSUE THREAD

**Issue by bistap** [dspencer-kc/mawd-pm#5]
I am currently attempting to reorder tests for our residents, which will be collected tomorrow, Thursday.  I am running into a very strange problem.  Each time I select a resident to reorder, the new requisition is auto-populating the incorrect DOB – each one is one day off.  For example 2/2/1951 becomes 2/1/1951, 8/1/1934 becomes 7/31/1934…..its VERY strange.  So far I have reordered for 10 patients, and the exact thing has occurred with all 10.  I thought I was crazy, so I looked at the actual results within the MAWD portal, and the results reflect the CORRECT DOB, but each time I attempt the reorder the DOB populates incorrectly.  Has this been an issue with any of the other communities you service?  I would hate to overlook one as we are reordering, and have it placed on hold or rejected if the DOB on the sample does not match the manifest as a result of this glitch

**Comment by ebergee** [comment]
Did some test patients today and they're all still populating the incorrect dob

**Comment by bistap** [comment]
@ebergee Just pushed the fix to test

**Comment by ebergee** [comment]
test patient today looks good. will close this issue.
