### ISSUE TITLE
Supplies Order improvements

### ISSUE THREAD

**Issue by ebergee** [dspencer-kc/mawd-pm#59]
- Move up item "UN 3373 FedEx Mailer" on the list
- If you edit any supply details/change values and then click refresh, it reverts to the prior value

**Comment by pj-issues** [comment]
@ebergee Could you try to update the supplies now. It should work.
If it does, the list that client see is ordered alphabetically right now. So technically if "UN3373 FedEx Mailer" is updated to Fedex Mailer UN3373. It will move up the list for the clients.

Let me know if you still can't update the supply list.
